import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Box from "@mui/material/Box";
import DrawerAppBar from "../components/NavBar";
import { HistoryProvider } from "@/contexts/HistoryContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "NextJS Chatbot",
  description: "Generated by create next app and Gemini API",
  icons: "/favicon.ico",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Bootstrap CSS */}
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
        />
      </head>
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HistoryProvider>
          <Box sx={{ display: "flex" }}>
            <DrawerAppBar />
            <div className="flex-auto justify-center p-5 mt-8">{children}</div>
          </Box>
        </HistoryProvider>
      </body>
    </html>
  );
}
